[package]
name = "messaging_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.24"
local-ip-address = "0.5.1"
threadpool = "1.8.1"
